config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions"}

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  get "up" => "rails/health#show", :as => :rails_health_check

  root "teams#index"

  get "redirect_page", to: "pages#redirect_page"

  resources :users do
    resource :profile
    collection do
      put :set_current_team
    end
  end

  resources :profiles, only: [:show]

  resources :teams do
    member do
      post :update_current_team
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/membership.rb
# == Schema Information
#
# Table name: memberships
#
#  id         :bigint           not null, primary key
#  user_id    :bigint           not null
#  team_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id              :bigint           not null, primary key
#  user_id         :bigint           not null
#  full_name       :string
#  profile_picture :string
#  bio             :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/team.rb
# == Schema Information
#
# Table name: teams
#
#  id          :bigint           not null, primary key
#  name        :string           not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Team < ApplicationRecord
  has_many :memberships
  has_many :users, through: :memberships

  validates :name, presence: true

  def user_has_role?(user, role)
    membership = memberships.find_by(user_id: user.id)
    membership.present? && user.role == role
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  first_name             :string           default(""), not null
#  last_name              :string           default(""), not null
#  username               :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  current_team_id        :bigint
#  sign_in_count          :integer          default(0), not null
#  role                   :string
#  avatar                 :string
#
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_one_attached :avatar

  has_one :profile, dependent: :destroy
  has_many :memberships
  has_many :teams, through: :memberships
  belongs_to :current_team, class_name: "Team", optional: true

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true, uniqueness: true, format: {with: /\A[a-zA-Z0-9_\.]*\z/}
  validates :email, presence: true, uniqueness: true
  # validates :avatar, content_type: ['image/jpeg', 'image/png', 'image/gif']
  # validates :role, inclusion: {in: %w[admin owner member], message: "%{value} is not a valid role"}

  attr_accessor :login

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
  end

  def admin?
    role == "admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :current_team

  def current_team
    @current_team ||= current_user&.current_team
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:password, :remember_me, :login])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[show edit update destroy]

  def index
    @profiles = Profile.all
  end

  def show
    if @profile.nil?
      @profile = Profile.create(user: @user)
    end
  end

  def new
    @profile = Profile.new
  end

  def edit
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user

    respond_to do |format|
      if @profile.save
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @profile.destroy!

    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_profile
    @user = User.find(params[:user_id])
    @profile = current_user.profile
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :bio, :user_id)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
    @role = current_user.role
  end

  def update
    @team = Team.find(params[:id])

    if @team.update(team_params)
      redirect_to team_path(@team), notice: "Team was successfully updated."
    else
      render :edit
    end
  end

  def edit
    @team = Team.find(params[:id])
  end

  def choose
    @teams = current_user.teams
  end

  def update_current_team
    team = Team.find(params[:team_id])
    current_user.update(current_team: team)
    redirect_to root_path, notice: "The active team has been successfully renewed."
  end

  private

  def team_params
    params.require(:team).permit(:name, :description, :other_attributes)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :email, :password, :password_confirmation, :current_password])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def after_sign_in_path_for(resource)
    if resource.sign_in_count == 1
      teams_path
    else
      super
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LeoTestProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%
=begin%>
 <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %> 
<%
=end%>

    <%
=begin%>
 <%= stylesheet_link_tag "application" %> 
<%
=end%>
    <%
=begin%>
 <%= javascript_importmap_tags %> 
<%
=end%>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/profiles/_form.html.haml
= form_with(model: profile, class: "contents") do |form|
  - if profile.errors.any?
    #error_explanation.bg-red-50.text-red-500.px-3.py-2.font-medium.rounded-lg.mt-3
      %h2
        = pluralize(profile.errors.count, "error")
        prohibited this profile from being saved:
      %ul
        - profile.errors.each do |error|
          %li= error.full_message
  .inline
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/profiles/_profile.html.haml
##{dom_id profile}
  - if action_name != "show"
    = link_to "Show this profile", profile, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    = link_to "Edit this profile", edit_profile_path(profile), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium"
    %hr.mt-6

app/views/profiles/edit.html.haml
.mx-auto.md:w-2/3.w-full
  %h1.font-bold.text-4xl
    Editing profile
  = render "form", profile: @profile
  = link_to "Show this profile", @profile, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to "Back to profiles", profiles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/profiles/index.html.haml
.w-full
  - if notice.present?
    #notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block
      = notice
  .flex.justify-between.items-center
    %h1.font-bold.text-4xl Profiles
    = link_to "New profile", new_profile_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"
  #profiles.min-w-full
    = render @profiles

app/views/profiles/new.html.haml
.mx-auto.md:w-2/3.w-full
  %h1.font-bold.text-4xl New profile
  = render "form", profile: @profile
  = link_to "Back to profiles", profiles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/profiles/show.html.haml
.mx-auto.md:w-2/3.w-full.flex
  .mx-auto
    - if notice.present?
      #notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block
        = notice
    = render @profile
    = link_to "Edit this profile", edit_profile_path(@profile), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
    .inline-block.ml-2
      = button_to "Destroy this profile", profile_path(@profile), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium"
    = link_to "Back to profiles", profiles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"